FROM node:18
WORKDIR /usr/local/apps/myapp

COPY package.json ./
RUN npm install && npm cache clean --force
RUN npx playwright install --with-deps
ENV PATH=/usr/local/myapp/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/myapp/dev
COPY tsconfig.json ./
COPY nodemon.json ./

COPY src ./src
COPY .env ./

EXPOSE ${PORT}

CMD ["npm", "run", "start:watch"]